
ADMINISTER KEY MANAGEMENT SET KEYSTORE
OPEN IDENTIFIED BY welcome1
CONTAINER = ALL;
/
ADMINISTER KEY MANAGEMENT 
CREATE KEY 
USING TAG 'root'
IDENTIFIED BY welcome1
WITH BACKUP USING 'root_create';
/
SELECT TAG, KEY_ID
FROM gv_$encryption_keys;
/

ADMINISTER KEY MANAGEMENT
USE KEY 'AQgnpLrKOk+fv61PBa8iNIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
USING TAG 'root'
IDENTIFIED BY welcome1
WITH BACKUP USING 'root_create';

/

-- BACK UP
ADMINISTER KEY MANAGEMENT BACKUP KEYSTORE 
USING 'pdb_create' 
FORCE KEYSTORE 
IDENTIFIED BY welcome1
TO 'C:/Users/wuuho/OneDrive/Desktop';
/
-- CHANGE PASSWORD
ADMINISTER KEY MANAGEMENT ALTER KEYSTORE PASSWORD 
FORCE KEYSTORE
IDENTIFIED BY
welcome1 SET welcome2 
WITH BACKUP USING 'pdb_create';