SELECT VALUE FROM v$option WHERE parameter = 'Oracle Label Security'; 
SELECT status FROM dba_ols_status WHERE name = 'OLS_CONFIGURE_STATUS';

ALTER PLUGGABLE DATABASE QLDTPDB OPEN READ WRITE; 
ALTER PLUGGABLE DATABASE QLDTPDB OPEN READ WRITE; 
-- B2
/
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS; 
/
EXEC LBACSYS.CONFIGURE_OLS; 

-- B3
shutdown IMMEDIATE; 
startup; 

-- B4
ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK 
CONTAINER = ALL; 


-- B5
CREATE USER OLS_TEST1 IDENTIFIED BY 1234 CONTAINER = CURRENT; 
GRANT CONNECT,RESOURCE TO OLS_TEST1; 
GRANT UNLIMITED TABLESPACE TO OLS_TEST1; 
GRANT SELECT ANY DICTIONARY TO OLS_TEST1; 

-- B6
GRANT EXECUTE ON sa_components TO OLS_TEST1 WITH GRANT OPTION; 
GRANT EXECUTE ON sa_user_admin TO OLS_TEST1 WITH GRANT OPTION; 
GRANT EXECUTE ON sa_label_admin TO OLS_TEST1 WITH GRANT OPTION; 
GRANT EXECUTE ON sa_policy_admin TO OLS_TEST1 WITH GRANT OPTION; 
GRANT EXECUTE ON sa_audit_admin TO OLS_TEST1 WITH GRANT OPTION; 
GRANT EXECUTE ON SA_SESSION TO OLS_TEST1 WITH GRANT OPTION; 
GRANT LBAC_DBA TO OLS_TEST1; 
GRANT EXECUTE ON sa_sysdba TO OLS_TEST1; 
GRANT EXECUTE ON to_lbac_data_label TO OLS_TEST1; 
GRANT region_policy_DBA TO OLS_TEST1; 

---B7 

INSERT INTO OLS_TEST1.THONGBAO(THONGBAO, NGAYTB, REGION_LABEL) VALUES('HELLOWORLD', TO_CHAR(sysdate), CHAR_TO_LABEL('region_policy', 'NV:SX:R40'));

SELECT * FROM OLS_TEST1.THONGBAO
EXECUTE SA_USER_ADMIN.SET_USER_PRIVS('region_policy','OLS_TEST1','FULL,PROFILE_ACCESS'); 

GRANT LBAC_SYS TO OLS_TEST1;
commit;
GRANT SELECT ON OLS_TEST1.THONGBAO TO N345;
GRANT SELECT ON OLS_TEST1.THONGBAO TO NHANVIEN;
GRANT SELECT ON OLS_TEST1.THONGBAO TO NVTRUONGPHONG;